# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
  armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:20.04"
  i386: "ghcr.io/home-assistant/i386-base-ubuntu"
#  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22"
#  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22"
#  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22"
#  i386: "ghcr.io/home-assistant/i386-base-python:3.13-alpine3.22"
